# Archivo de configuraci√≥n para el bot de Telegram
services:
  - type: web
    name: bot-telegram-ventas
    env: python
    plan: free
    pythonVersion: "3.12"
    buildCommand: "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
    startCommand: "python bot_telegram.py"

